name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Nimbus version to build"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - linux/amd64
          - linux/arm64/v8
          - linux/arm/v7

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: status-im/nimbus-eth2
          ref: ${{ inputs.version }}

      - name: Build for ${{ matrix.variant }}
        run: |
          PLATFORM=${{ fromJson('{ "linux/amd64": "Linux_amd64", "linux/arm64/v8": "Linux_arm64v8", "linux/arm/v7": "Linux_arm32v7" }')[matrix.variant] }}
          mkdir /home/user
          ln -s . /home/user/nimbus-eth2
          ./docker/dist/entry_point.sh $PLATFORM

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.variant }}
          path: ./build/nimbus_beacon_node

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
            type=semver,pattern={{major}},value=${{ inputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
